### ISSUE TITLE
Inconsistent tensor size, training with mn-att-ques-im-hist

### ISSUE THREAD

**Issue by enidvx** [batra-mlp-lab/visdial#13]
Hello,
I am trying to execute train.lua with mn-att-ques-im-hist encoder, I downloaded the  data_img_pool5.h file on the google drive link you provided on  issue #12  link: https://drive.google.com/open?id=0B-iGspODhEtrUXg5dXV5TlRJUmM 

I execute the model on CPU with:
`th train.lua -encoder mn-att-ques-im-hist -decoder gen -gpuid -1 -rnnHiddenSize 380 -numEpochs 40 -numLayers 1`

and I get the below error:
`/home/ubuntu/torch2/install/bin/luajit: /home/ubuntu/torch2/install/share/lua/5.1/nn/CAddTable.lua:16: inconsistent tensor size, expected r_ [400 x 512], t [400 x 512] and src [400 x 380] to have the same number of elements, but got 204800, 204800 and 152000 elements respectively at /home/ubuntu/torch2/pkg/torch/lib/TH/generic/THTensorMath.c:887
stack traceback:
        [C]: in function 'add'
        /home/ubuntu/torch2/install/share/lua/5.1/nn/CAddTable.lua:16: in function 'func'
        .../ubuntu/torch2/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        .../ubuntu/torch2/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        ./model.lua:229: in function 'forwardBackward'
        ./model.lua:74: in function 'trainIteration'
        train.lua:72: in main chunk
        [C]: in function 'dofile'
        ...ntu/torch2/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50`

Please can you tell how to solve this?
Regards,
Enid

**Comment by interritus1996** [comment]
You would be able to solve this issue if you keep `rnnHiddenSize` to the default value i.e. 512. I think somewhere in the implementation of this model, it assumes `rnnHiddenSize` to be 512. A quick fix would be to use 512 instead of 380.
