### ISSUE TITLE
bad argument #2 to 'add' (sizes do not match at /torch-addons/cutorch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:269)

### ISSUE THREAD

**Issue by krsandeep98** [batra-mlp-lab/visdial#24]
https://github.com/batra-mlp-lab/visdial/blob/3ffb761dc6725e2f5e70a8c8371c1c457cf57bbb/encoders/mn-att-ques-im-hist.lua#L74

This is the error which I am getting on running train.lua with mn-att-ques-im-hist encoder and gen decoder. And this error corresponds to the encoder forward pass in the forwardBackward function.
I am able to get it running by changing the _params.imgFeatureSize_ (whose value is 4096) in the above-mentioned line to 512.
@abhshkdz

**Comment by abhshkdz** [comment]
Could you paste the exact command you ran?

And are you sure you followed this note in the readme?

<img width="904" alt="screen shot 2018-06-09 at 1 57 26 pm" src="https://user-images.githubusercontent.com/1156489/41194663-47864fea-6bed-11e8-95fc-33679d01e3ac.png">

**Comment by krsandeep98** [comment]
I changed the parameters directly in the opts.lua file and there the value of imgSpatialSize was 14 and imgFeatureSize was 4096.

**Comment by abhshkdz** [comment]
It might be easier to use something like this instead:

`th train.lua -encoder mn-att-ques-im-hist -decoder gen -imgSpatialSize 14 -imgFeatureSize 512`
