### ISSUE TITLE
Why is the dimension of input image features in attention case 14x14x4096? 

### ISSUE THREAD

**Issue by krsandeep98** [batra-mlp-lab/visdial#25]
https://github.com/batra-mlp-lab/visdial/blob/3ffb761dc6725e2f5e70a8c8371c1c457cf57bbb/model.lua#L265
Shouldn't the dimensions be 14x14x512 in case of using the image features for the attention-based encoders?
I am facing this issue (in the encoder forward pass of forwardBackward function) while running the mn-att-ques-im-hist encoder and gen decoder. 
Exact problem is also mentioned in #24

**Comment by abhshkdz** [comment]
Same as #24
