### ISSUE TITLE
Issue with prepro.py at line 150.

### ISSUE THREAD

**Issue by tarun005** [batra-mlp-lab/visdial#26]
Why is the loop over 'j' at line no. 150 in prepro.py script necessary, when at test time, we only need to look at the options in the last round.

**Comment by satwikkottur** [comment]
@kdexd Here's the link for reference: https://github.com/batra-mlp-lab/visdial/blob/master/data/prepro.py#L150

**Comment by kdexd** [comment]
You're right @tarun005 . Luckily it's not causing any harm. But it's redundant now.

**Comment by kdexd** [comment]
Fixed it in 06a7b81 , thanks!
