### ISSUE TITLE
dimension doesn't match during evalution

### ISSUE THREAD

**Issue by DJJune** [batra-mlp-lab/visdial#27]
###function Model:predict  in  model.lua line215
`ranks[{{startId, nextStartId - 1}, {}}] = self:retrieveBatch(batch)
                                                            :view(nextStartId - startId, -1, self.params.numOptions);
`
the size of  `self:retrieveBatch(batch)` is 300X1 while it is going to be reshaped to 10X300
So, there is a error that `The number of covered elements is not a multiple of all elements.`

**Comment by kdexd** [comment]
Hi @DJJune can you please paste the printed table of opts when you run `th evaluate.lua`?

**Comment by DJJune** [comment]
`{
  useGt : false,
  inputQues : "data/visdial_data.h5",
  batchSize : 30,
  split : "val",
  loadPath : "core_models/lf-ques-gen-vgg16-18.t7",
  inputJson : "data/visdial_params.json",
  saveRanks : false,
  saveRankPath : "logs/ranks.json",
  backend : "cudnn",
  gpuid : 0,
  inputImg : "data/data_img_vgg16_relu7.h5"
}
`The image features and model are downloaded from your repository. 
Thank you!

**Comment by kdexd** [comment]
@DJJune: thanks for this info. I managed to localize the error and add a fix. It works on my end. Can you pull the latest source and verify if it works?

**Comment by abhshkdz** [comment]
This should be fixed now.

**Comment by DJJune** [comment]
Hi! @abhshkdz @kdexd 
Thanks, now I can generate the `logs/ranks.json`.
However, I wanted to get the result of `recall@k`, so I used the command that `th evaluate.lua -loadPath core_models/lf-ques-gen-vgg16-18.t7  -inputImg data/data_img_vgg16_relu7.h5  -gpuid 0 -useGt`  and the opts are `
{
  useGt : true
  inputQues : "data/visdial_data.h5"
  batchSize : 30
  split : "val"
  loadPath : "core_models/lf-ques-gen-vgg16-18.t7"
  inputJson : "data/visdial_params.json"
  saveRanks : false
  saveRankPath : "logs/ranks.json"
  backend : "cudnn"
  gpuid : 0
  inputImg : "data/data_img_vgg16_relu7.h5"
}
`. The error `sizes do not match` occurred in function 'retrieve' in 'model.lua'
Could you please help me to solve this problem? Thanks!

**Comment by abhshkdz** [comment]
Ah, this was recently fixed in https://github.com/batra-mlp-lab/visdial/commit/67aae72751adacbb8995a5dfdc3bff8a494ef7ed.

Could you pull the latest changes and try again please.

**Comment by DJJune** [comment]
It works! Thanks!
