### ISSUE TITLE
Pytorch starter code

### ISSUE THREAD

**Issue by shubhamagarwal92** [batra-mlp-lab/visdial#28]
Hi,

Do you guyz plan to release starter code in pytorch for the challenge? [visdial-rl](https://github.com/batra-mlp-lab/visdial-rl) does provide some insights but is tailored more for Visual Dialog Agents as described in the paper "Learning Cooperative Visual Dialog Agents with Deep Reinforcement Learning"

**Comment by nirbhayjm** [comment]
Hi, [visdial-rl](https://github.com/batra-mlp-lab/visdial-rl) is tailored more towards the two-agent setup but does support Visual Dialog training and evaluation i.e. just the Answering agent (A-Bot). The [training](https://github.com/batra-mlp-lab/visdial-rl#training) and [evaluation](https://github.com/batra-mlp-lab/visdial-rl#evaluation) can be used with A-Bot alone to do supervised training on the VisDial 0.5 and 0.9 datasets with evaluation on the standard VisDial metrics.

Though the codebase supports just HRE (Hierarchical recurrent encoder and decoder) in [hre.py](https://github.com/batra-mlp-lab/visdial-rl/blob/master/visdial/models/encoders/hre.py), it can still serve as a starting point for building your own models for visual dialog.

**Comment by kdexd** [comment]
Hi @shubhamagarwal92, [visdial-rl](https://www.github.com/batra-mlp-lab/visdial-rl) will have some enhancements - we would add a section in _README_describing the usage of that codebase as a starter code for Visual Dialog Challenge. Please watch out for announcements on [Discord](https://discordapp.com/invite/TQQQrfY) about this soon. Thanks!
