### ISSUE TITLE
Issue on extracting image feature

### ISSUE THREAD

**Issue by yellowjs0304** [batra-mlp-lab/visdial#31]
Hi i'm getting problem on extracting image feature.
I ran this command, "th prepro_img_vgg16.lua -imageRoot ~/Desktop/2014/ -gpuid 0"
It returns
```
/home/ai8503/torch/install/bin/lua: ...me/ai8503/torch/install/share/lua/5.1/trepl/init.lua:389: ...me/ai8503/torch/install/share/lua/5.1/trepl/init.lua:389: ...home/ai8503/torch/install/share/lua/5.1/hdf5/ffi.lua:56: expected align(#) on line 579
stack traceback:
	[C]: in function 'error'
	...me/ai8503/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	prepro_img_vgg16.lua:3: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: ?
```
How can I fix this?

**Comment by abhshkdz** [comment]
Not completely certain of the fix, but might be worth trying https://github.com/deepmind/torch-hdf5/issues/79#issuecomment-274246061

**Comment by yellowjs0304** [comment]
I appreciate your help, but I have not found the solution.

**Comment by wanyao1992** [comment]
@yellowjs0304 have you solved the problem? I encounter the same problem.

**Comment by abhshkdz** [comment]
@wanyao1992 @yellowjs0304 could you try this with luajit instead of lua 5.1 please. That seems to have fixed it for a bunch of people on the issue referenced above.

**Comment by ChoYS96** [comment]
I solved the problem by installing luajit!
And I install the hdf5 version 1.10.

**Comment by yellowjs0304** [comment]
@wanyao1992 @ChoYS96 
No way, it is not a good solution.
I installed the LuaJit instead of lua5.1 and the issue about line 579 is gone.
But in extracting the image feature, It occurs out of memory error.
