### ISSUE TITLE
Wrong filename for visdial_data_{}.h5 in VisDial v1.0

### ISSUE THREAD

**Issue by DJJune** [batra-mlp-lab/visdial#35]
@abhshkdz Hi,My code could not get the val question in  `visdial_data_trainval.h5` and I found the val set in the `train.h5`
Could you please check whether the filename is wrong in VisDial v1.0?

**Comment by abhshkdz** [comment]
Hey @DJJune, these are accurate. `visdial_data_trainval.h5` combines v1.0 train+val into `train`, and has v1.0 test as `test`.

And `visdial_data_train.h5` is for training on v1.0 train (`train`), and evaluating on v1.0 val (`val`) and v1.0 test (`test`).
