### ISSUE TITLE
About sampling

### ISSUE THREAD

**Issue by ruizhaogit** [batra-mlp-lab/visdial#4]
Hi,

In your code here [model.lua](https://github.com/batra-mlp-lab/visdial/blob/master/model.lua#L515), shouldn't the decoder first couple with the encoder, so the sampling could also conditioned on the image features and the previous conversions?

It seems to me that, the sampling is only based on the word in the previous time-step, without the knowledge of the image features and so on.

Best,
Rui

**Comment by abhshkdz** [comment]
Coupling is already taken care of here: [model.lua#L385](https://github.com/batra-mlp-lab/visdial/blob/master/model.lua#L385), [model.lua#L225](https://github.com/batra-mlp-lab/visdial/blob/master/model.lua#L225).

**Comment by ruizhaogit** [comment]
Thanks!
