### ISSUE TITLE
How did you generate Figure 5 in your paper?

### ISSUE THREAD

**Issue by MottoX** [batra-mlp-lab/visdial#41]
Hi,
I would like to know what tool you used to generate Figure 5 in your paper.
![image](https://user-images.githubusercontent.com/6220861/55173885-6c56be80-51b7-11e9-9119-79efddb0ce25.png)

Thank you!

**Comment by abhshkdz** [comment]
We used d3; you can see a version of it [here](https://visualdialog.org/visualize).
