### ISSUE TITLE
Beam search with length normalized log likelihood?

### ISSUE THREAD

**Issue by ruizhaogit** [batra-mlp-lab/visdial#5]
Hi guys,

About [beam search here](https://github.com/batra-mlp-lab/visdial/blob/master/model.lua#L477), if I understand it correctly, this is the normal beam search without length normalized log likelihood, then it should tend to find a shorter sequence, right? Did you also try the beam search with the length normalized log likelihood?

Thank you!

Best,
Rui

**Comment by abhshkdz** [comment]
Yup, the current version prefers shorter sequences and we did try both. In terms of retrieval performance as described in the paper, beam search with length normalization performs better on some metrics and worse on others, so there was no clear choice. We picked this and went ahead with it.
