### ISSUE TITLE
Where is the code concatenating the t-rounds of history for lf-encoder?

### ISSUE THREAD

**Issue by ruizhaogit** [batra-mlp-lab/visdial#6]
Hi Visdial Team,

Thank for the great code!
I am a little lost. Could you please point me where is the code for concatenating the t-rounds of the history question and answers for the late fusion encoder?

Thank you!

Best,
Rui

**Comment by abhshkdz** [comment]
Ah, good catch! I probably must've messed up while cleaning up code for release. :( The current late fusion implementation is a seq2seq model from 1-round history and question to response. Will fix it.

FWIW, the numbers in the paper are consistent, i.e. for the model that concatenates all previous history.

**Comment by ruizhaogit** [comment]
Good to know. Thanks!

**Comment by abhshkdz** [comment]
093d5004da63a0770fa9fe5f3ce66bc2ecfdd426 should fix it. I'll update LF pretrained models in a few days.

**Comment by abhshkdz** [comment]
Updated the pretrained LF models [here](https://computing.ece.vt.edu/~abhshkdz/visdial/models/).
