### ISSUE TITLE
Why use "CAddTable" instead of concatenating features in the memory network?

### ISSUE THREAD

**Issue by ruizhaogit** [batra-mlp-lab/visdial#7]
Hi Visdial Team,

I have a question regarding to combining the history and question features in the memory network encoder. Why do you use [element add](https://github.com/batra-mlp-lab/visdial/blob/master/encoders/mn-ques-im-hist.lua#L68) instead of simply concatenating like you did in the late fusion encoder? Is there any advantages in this?

Thank you in advance!

Best,
Rui

**Comment by abhshkdz** [comment]
To be as close to the [Memory Networks](https://arxiv.org/abs/1503.08895) paper as possible. We haven't tried concatenating. Let us know how things go if you do :)

**Comment by ruizhaogit** [comment]
Alright :)
